name: $(Build.DefinitionName).$(Build.SourceBranchName).$(Date:yyyyMMdd).$(Rev:r)

pool: 'Hyrule'

trigger:
- feature/pipelines

stages:
- stage: Build_nugets
  displayName: 'Build nugets'
  jobs:
    - job: Build
      displayName: 'Build'
      variables:
        projects: '**/*.csproj'
        unitTestProjects: '**/*.Tests.csproj'
        buildConfiguration: 'Release'
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restore packages'
          inputs:
            command: 'restore'
            projects: '$(projects)'
        - task: DotNetCoreCLI@2
          displayName: 'Compile the solution'
          inputs:
            command: build
            projects: $(projects)
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Run unit tests'
          inputs:
            command: test
            projects: $(unitTestProjects)
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
            displayName: 'Install dotnet-stryker'
            inputs:
              command: custom
              custom: tool
              arguments: restore
        - task: PowerShell@2
          displayName: 'Run dotnet-stryker'
          inputs:
            workingDirectory: '$(Build.SourcesDirectory)/Mutation/Mutation.Services.Tests'
            targetType: inline
            script: dotnet stryker -r
        - task: PublishMutationReport@0
          displayName: 'Publish Mutation test report'
          inputs:
            reportPattern: '**/mutation-report.html'