name: $(Build.DefinitionName).$(Build.SourceBranchName).$(Date:yyyyMMdd).$(Rev:r)

pool: 'Hyrule'

pr:
- main

trigger:
- feature/pipelines

stages:
- stage: Build_nugets
  displayName: 'Build nugets'
  jobs:
    - job: Build
      displayName: 'Build'
      variables:
        projects: '**/*.csproj'
        unitTestProjects: '**/*.Tests.csproj'
        buildConfiguration: 'Release'
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restore packages'
          inputs:
            command: 'restore'
            projects: '$(projects)'
        - task: DotNetCoreCLI@2
          displayName: 'Compile the solution'
          inputs:
            command: build
            projects: $(projects)
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Run unit tests'
          inputs:
            command: test
            projects: $(unitTestProjects)
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Install dotnet-stryker'
          inputs:
            command: 'custom'
            custom: 'tool'
            arguments: 'restore'
            workingDirectory: '$(Build.SourcesDirectory)/Mutation'
        - task: PowerShell@2
          displayName: 'Run dotnet-stryker'
          condition: eq(variables['Build.SourceBranchName'], 'pipelines')
          inputs:
            targetType: inline
            #workingDirectory: '$(Build.SourcesDirectory)'
            #script: '.\Sandbox.Technic.exe $(Build.SourcesDirectory)/Mutation *.Tests'
            workingDirectory: '$(Build.SourcesDirectory)/Mutation/Mutation.Services.Tests'
            script: dotnet stryker
        - task: PowerShell@2
          displayName: 'Run dotnet-stryker (compare via Pull request)'
          condition: eq(variables['Build.SourceBranchName'], 'merge')
          inputs:
            targetType: inline
            workingDirectory: '$(Build.SourcesDirectory)/Mutation/Mutation.Services.Tests'
            script: dotnet stryker -compare -bsl Dashboard -dk $(Stryker.Dashboard.ApiKey) -version $(System.PullRequest.SourceBranch) -project github.com/abeauchamp96/Sandbox.Mutation
        - task: PublishMutationReport@0
          displayName: 'Publish Mutation test report'
          inputs:
            reportPattern: '**/mutation-report.html'